# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, null=True, verbose_name='ip地址')),
                ('data', models.CharField(max_length=64, null=True, verbose_name='数据')),
            ],
        ),
    ]
